[package]
name = "randomexample3"
version = "1.0.0"
authors = ["argenestel","saurx"]

[addresses]
getrandnumb="_"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

